### ISSUE TITLE
no setup docs

### ISSUE THREAD

**Issue by farkerhaiku** [jprobinson/newshound#4]
This repo should provide some setup docs :p

**Comment by jprobinson** [comment]
I don't have time to make any official docs but it goes like this:

(1) Make a GCP project, enable app engine
(2) Set up a MongoDB instance in that project on GCE
(3) Create a ["serverless VPC connector"](https://cloud.google.com/vpc/docs/configure-serverless-vpc-access) to enable App Engine to access MongoDB
(4) Create 2 PubSub topics: ["alerts" and "events"](https://github.com/jprobinson/newshound/blob/master/fetch/fetchd/main.go#L32-L37)
(5) Deploy the [`np_extractor` service](https://github.com/jprobinson/newshound/blob/master/np_extractor/app.yaml) using [App Engine tooling](https://cloud.google.com/appengine/docs/standard/python/tools/uploadinganapp). 
(6) To fetch email from IMAP, parse it, save it to MongoDB, and emit events to PubSub you need to deploy `fetchd`. It will need IMAP/email credentials and MongoDB credentials. Those are currently set up to be injected into the environment variables when deployed via `fetch/fetchd/app.yaml`. The serverless connector created in (3) will need to be wired into that same yaml file. [Deployment guide here](https://cloud.google.com/appengine/docs/standard/go/testing-and-deploying-your-app)
(7) To expose the data in MongoDB via an API, you can deploy the `api` service and `web` to get the web UI on top both use the same GAE deployment tools.
(8) If you want Slack alerts or Twitter posts, you can deploy the `bark` service. The credentials are wired into the `bark/barkd/app.yaml` file.
